"""F&L name nullable

Revision ID: 0f33526b6753
Revises: 8512f48fa8fb
Create Date: 2025-07-12 15:11:50.047545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f33526b6753'
down_revision: Union[str, Sequence[str], None] = '8512f48fa8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('people', 'last_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'last_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('people', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
