"""added webhook response json

Revision ID: 10511cfce993
Revises: c3f33d50f6d0
Create Date: 2025-07-12 17:23:30.038710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10511cfce993'
down_revision: Union[str, Sequence[str], None] = 'c3f33d50f6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_details', sa.Column('webhook_respomse_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_details', 'webhook_respomse_json')
    # ### end Alembic commands ###
