"""added webhook phone number

Revision ID: 63d6a9e1195b
Revises: 17e32035e4b8
Create Date: 2025-07-12 17:25:55.517458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d6a9e1195b'
down_revision: Union[str, Sequence[str], None] = '17e32035e4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_details', sa.Column('webhook_phone_number', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_details', 'webhook_phone_number')
    # ### end Alembic commands ###
