"""added phone number type to str

Revision ID: 820778254e4d
Revises: f7655f19a71f
Create Date: 2025-07-12 17:35:50.391966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '820778254e4d'
down_revision: Union[str, Sequence[str], None] = 'f7655f19a71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person_details', 'phone_numbers',
               existing_type=mysql.JSON(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('person_details', 'webhook_phone_number',
               existing_type=mysql.JSON(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person_details', 'webhook_phone_number',
               existing_type=sa.String(length=64),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('person_details', 'phone_numbers',
               existing_type=sa.String(length=64),
               type_=mysql.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
