"""add personal contact cols

Revision ID: 88781989ba93
Revises: c9ed00ee8dfc
Create Date: 2025-07-07 23:39:23.747634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88781989ba93'
down_revision: Union[str, Sequence[str], None] = 'c9ed00ee8dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('personal_email', sa.String(length=255), nullable=True))
    op.add_column('people', sa.Column('personal_phone', sa.String(length=64), nullable=True))
    op.add_column('people', sa.Column('phone_verification_status', sa.String(length=32), nullable=True))
    op.add_column('people', sa.Column('phones_raw_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'phones_raw_json')
    op.drop_column('people', 'phone_verification_status')
    op.drop_column('people', 'personal_phone')
    op.drop_column('people', 'personal_email')
    # ### end Alembic commands ###
