"""create initial tables

Revision ID: bff566a003f2
Revises: 
Create Date: 2025-07-07 20:00:58.752391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff566a003f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('apollo_org_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain_resolved', sa.String(length=255), nullable=True),
    sa.Column('domain_entered', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('location_city', sa.String(length=128), nullable=True),
    sa.Column('location_country', sa.String(length=64), nullable=True),
    sa.Column('is_enriched', sa.Boolean(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apollo_org_id')
    )
    op.create_table('people',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('apollo_person_id', sa.String(length=40), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('location_city', sa.String(length=128), nullable=True),
    sa.Column('location_country', sa.String(length=64), nullable=True),
    sa.Column('is_enriched', sa.Boolean(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apollo_person_id')
    )
    op.create_table('company_people',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_details',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('blog_url', sa.String(length=255), nullable=True),
    sa.Column('angellist_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('primary_phone', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('alexa_ranking', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('linkedin_uid', sa.String(length=40), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('publicly_traded_symbol', sa.String(length=20), nullable=True),
    sa.Column('publicly_traded_exchange', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('crunchbase_url', sa.String(length=255), nullable=True),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('estimated_num_employees', sa.Integer(), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('secondary_industries', sa.JSON(), nullable=True),
    sa.Column('snippets_loaded', sa.Boolean(), nullable=True),
    sa.Column('industry_tag_id', sa.String(length=40), nullable=True),
    sa.Column('industry_tag_hash', sa.JSON(), nullable=True),
    sa.Column('retail_location_count', sa.Integer(), nullable=True),
    sa.Column('raw_address', sa.String(length=512), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('owned_by_organization_id', sa.String(length=40), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('suborganizations', sa.JSON(), nullable=True),
    sa.Column('num_suborganizations', sa.Integer(), nullable=True),
    sa.Column('annual_revenue_printed', sa.String(length=50), nullable=True),
    sa.Column('annual_revenue', sa.Integer(), nullable=True),
    sa.Column('total_funding', sa.Integer(), nullable=True),
    sa.Column('total_funding_printed', sa.String(length=50), nullable=True),
    sa.Column('latest_funding_round_date', sa.DateTime(), nullable=True),
    sa.Column('latest_funding_stage', sa.String(length=50), nullable=True),
    sa.Column('funding_events', sa.JSON(), nullable=True),
    sa.Column('technology_names', sa.JSON(), nullable=True),
    sa.Column('org_chart_root_people_ids', sa.JSON(), nullable=True),
    sa.Column('org_chart_sector', sa.String(length=255), nullable=True),
    sa.Column('org_chart_removed', sa.Boolean(), nullable=True),
    sa.Column('org_chart_show_department_filter', sa.Boolean(), nullable=True),
    sa.Column('account_id', sa.String(length=40), nullable=True),
    sa.Column('departmental_head_count', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('person_details',
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url_full', sa.String(length=255), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('email_status', sa.String(length=32), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('extrapolated_email_confidence', sa.String(length=32), nullable=True),
    sa.Column('contact_id', sa.String(length=40), nullable=True),
    sa.Column('contact_blob', sa.JSON(), nullable=True),
    sa.Column('revealed_for_current_team', sa.Boolean(), nullable=True),
    sa.Column('is_likely_to_engage', sa.Boolean(), nullable=True),
    sa.Column('intent_strength', sa.String(length=64), nullable=True),
    sa.Column('show_intent', sa.Boolean(), nullable=True),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('subdepartments', sa.JSON(), nullable=True),
    sa.Column('functions', sa.JSON(), nullable=True),
    sa.Column('contact_emails', sa.JSON(), nullable=True),
    sa.Column('phone_numbers', sa.JSON(), nullable=True),
    sa.Column('typed_custom_fields', sa.JSON(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_details')
    op.drop_table('organization_details')
    op.drop_table('company_people')
    op.drop_table('people')
    op.drop_table('companies')
    # ### end Alembic commands ###
