"""add raw_json to organization_details

Revision ID: c9ed00ee8dfc
Revises: cf0c896366fa
Create Date: 2025-07-07 23:04:45.116128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ed00ee8dfc'
down_revision: Union[str, Sequence[str], None] = 'cf0c896366fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_details', sa.Column('raw_json', sa.JSON(), nullable=True))
    op.add_column('person_details', sa.Column('raw_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_details', 'raw_json')
    op.drop_column('organization_details', 'raw_json')
    # ### end Alembic commands ###
