"""add company_search tables

Revision ID: cf0c896366fa
Revises: bff566a003f2
Create Date: 2025-07-07 21:20:20.175262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0c896366fa'
down_revision: Union[str, Sequence[str], None] = 'bff566a003f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_search_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query_name', sa.String(length=255), nullable=True),
    sa.Column('partial_results', sa.Boolean(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('per_page', sa.Integer(), nullable=True),
    sa.Column('total_entries', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_search_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('apollo_org_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('publicly_traded_symbol', sa.String(length=20), nullable=True),
    sa.Column('publicly_traded_exchange', sa.String(length=20), nullable=True),
    sa.Column('alexa_ranking', sa.Integer(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['company_search_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_search_results')
    op.drop_table('company_search_runs')
    # ### end Alembic commands ###
